from flask import Flask, render_template
import random

app = Flask(__name__)

frases = [
    "Eres un alma eterna viviendo una experiencia humana.",
    "Todo lo que buscas ya está dentro de ti.",
    "La conciencia es la llave que abre todas las puertas.",
    "No eres tus pensamientos; eres quien los observa.",
    "El universo te guía en cada paso, aunque no lo veas.",
    "Suelta lo que no vibra contigo y ábrete a lo nuevo.",
    "La sincronicidad no es casualidad, es el lenguaje del alma.",
    "Tu respiración es un portal hacia el presente.",
    "Despertar duele, pero vivir dormido duele más.",
    "Cada emoción es un mensaje del alma, escúchala.",
    "La vibración atrae lo que emites, no lo que deseas.",
    "Donde pones tu atención, creas realidad.",
    "No estás solo, estás siendo guiado siempre.",
    "La oscuridad no es mala, es parte del proceso.",
    "El silencio interior es tu templo más sagrado.",
    "La aceptación es el inicio de la sanación.",
    "Cuando sueltas el control, llega la magia.",
    "El alma no tiene prisa, solo el ego corre.",
    "Todo es energía; cuida lo que piensas, sientes y hablas.",
    "Tu frecuencia crea tu experiencia.",
    "La intuición es la voz de tu yo superior.",
    "El dolor abre el corazón a una verdad más alta.",
    "Eres canal de luz en un mundo que necesita sanar.",
    "La vida no es una prueba, es una oportunidad de recordar.",
    "Las respuestas llegan cuando el ruido se apaga.",
    "Confía, aunque no entiendas el camino.",
    "Cada encuentro tiene un propósito más allá de lo visible.",
    "No eres víctima, eres creador.",
    "La expansión comienza cuando sueltas la resistencia.",
    "Estás justo donde debes estar, siempre.",
    "El universo no castiga, solo refleja.",
    "Cuando agradeces, te alineas con la abundancia.",
    "La energía que das es la que regresa.",
    "La compasión hacia ti mismo es el acto más espiritual.",
    "El despertar no te hace mejor, te hace más consciente.",
    "Perdonar no es olvidar, es liberarte.",
    "Honra tus sombras, también son parte de tu luz.",
    "La conciencia se expande cuando dejas de defender tu historia.",
    "El momento presente es el único real.",
    "No hay error, solo aprendizaje.",
    "Eres amor en forma humana.",
    "Tus heridas no te definen, tu luz sí.",
    "Cada día es una oportunidad para elegir distinto.",
    "Respira profundo, vuelve a ti.",
    "La espiritualidad no es huir del mundo, es habitarlo con el alma despierta.",
    "Todo lo que llega, viene a enseñarte algo.",
    "Tu historia tiene un propósito más grande del que imaginas.",
    "Despertar es recordar quién eras antes de que el mundo te dijera quién deberías ser.",
    "Tu esencia es intocable, eterna y pura.",
    "Nada externo puede darte la paz que nace en tu interior.",
    "El caos es una bendición disfrazada de movimiento.",
    "Eres parte del todo, y el todo vive en ti.",
    "Ama sin apego, suelta sin miedo.",
    "La fe es ver con el alma lo que los ojos no comprenden.",
    "No estás roto, estás en proceso.",
    "Ser espiritual no es perfecto, es auténtico.",
    "Todo tiene su ritmo divino, confía.",
    "Sintoniza con tu alma, no con tus miedos.",
    "La magia ocurre fuera de tu zona cómoda.",
    "Cada emoción reprimida se transforma en bloqueo.",
    "Cuando sanas tú, sanas tu linaje.",
    "La verdad no se aprende, se recuerda.",
    "Las almas afines se reconocen por vibración, no por apariencia.",
    "Las señales están en todas partes, solo necesitas presencia.",
    "Tu vulnerabilidad es tu mayor fortaleza.",
    "La mente grita, el alma susurra.",
    "Camina ligero, lo que es tuyo no te lo puede quitar nadie.",
    "El amor verdadero empieza contigo.",
    "Eres suficiente, ahora y siempre.",
    "El propósito no se busca, se revela.",
    "No hay destino final, solo evolución.",
    "Estás despertando, y eso lo cambia todo.",
    "La conexión con tu ser superior te libera del sufrimiento.",
    "Todo es temporal, menos tu esencia.",
    "La luz no necesita luchar contra la oscuridad, solo encenderse.",
    "La transformación ocurre cuando dejas de resistirla.",
    "Eres parte de un plan más grande que tu ego.",
    "Las respuestas viven en tu silencio interior.",
    "No te apures por sanar, cada alma tiene su ritmo.",
    "Todo proceso espiritual es individual, pero jamás solitario.",
    "Eres semilla de una nueva conciencia.",
    "La gratitud abre portales invisibles.",
    "La espiritualidad no es moda, es verdad interna.",
    "Eres guía, incluso cuando te sientes perdido.",
    "El alma no miente, el ego sí.",
    "Tu sombra no es tu enemiga, es tu maestra.",
    "Confía en lo que sientes, aunque no lo entiendas.",
    "La autenticidad es la forma más pura de conexión.",
    "El juicio aleja, la comprensión une.",
    "A veces perderte es la forma de volver a ti.",
    "El universo vibra con tu intención.",
    "Sanar no es volver al pasado, es liberar lo que aún duele.",
    "No todos te entenderán, pero no todos están destinados a caminar contigo.",
    "Eres canal, puente y fuente.",
    "Los ciclos cierran cuando entiendes el aprendizaje.",
    "Vivir conscientemente es un acto revolucionario.",
    "Nada de lo que viene de tu alma es egoísta.",
    "No necesitas saberlo todo, solo confiar en lo que sientes.",
    "La sabiduría espiritual se vive, no se memoriza.",
    "El despertar no es un destino, es un camino eterno.",
    "Tu energía habla antes que tus palabras.",
    "Eres amor recordando que lo es.",
    "El universo es mental, emocional y espiritual.",
    "Gracias por elegir despertar en este tiempo. Estás ayudando al todo."
]

@app.route("/")
def inicio():
    frase = random.choice(frases)
    return render_template("inicio.html", frase=frase)

if __name__ == "__main__":
    app.run(debug=True)
